SELECT B.YEAR, B.MONTH,A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
INNER JOIN (
            SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH , USER_ID
            FROM ONLINE_SALE
            ) B
ON A.USER_ID=B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY B.YEAR, B.MONTH, A.GENDER
ORDER BY B.YEAR, B.MONTH, A.GENDER