SELECT
    C.CAR_ID, C.CAR_TYPE,
    C.DAILY_FEE * (1-D.DISCOUNT_RATE) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT A.CAR_ID, A.START_DATE, A.END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN (
        SELECT CAR_ID, MAX(HISTORY_ID) AS MAX_HISTORY_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID) B
        ON A.HISTORY_ID = B.MAX_HISTORY_ID
        WHERE TO_CHAR(START_DATE, 'YYYY-MM-DD') > '2022-11-30'
        OR TO_CHAR(END_DATE, 'YYYY-MM-DD') < '2022-11-01') H
ON C.CAR_ID = H.CAR_ID
JOIN (
    SELECT CAR_TYPE, (DISCOUNT_RATE * 0.01) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE SUBSTR(DURATION_TYPE, 0, INSTR(DURATION_TYPE, '일', 1, 1)-1) = '30'
) D
ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV', '세단')
AND C.DAILY_FEE * (1-D.DISCOUNT_RATE) * 30 BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC;