SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A
INNER JOIN(
            SELECT CART_ID
            FROM CART_PRODUCTS
            WHERE NAME='Yogurt'
            )B
ON A.CART_ID=B.CART_ID
WHERE A.NAME='Milk'
ORDER BY CART_ID;