SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, A.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
        FROM REST_INFO 
        GROUP BY FOOD_TYPE)A , REST_INFO B

WHERE B.FOOD_TYPE=A.FOOD_TYPE AND B.FAVORITES=A.FAVORITES
ORDER BY B.FOOD_TYPE DESC