SELECT EXTRACT(YEAR FROM A.SALES_DATE) AS YEAR ,EXTRACT(MONTH FROM A.SALES_DATE)AS MONTH, COUNT(DISTINCT A.USER_ID) AS PURCHAED_USERS, ROUND(COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(USER_ID)
                FROM USER_INFO
                WHERE EXTRACT(YEAR FROM JOINED)=2021),1) AS PURCHASED_RATIO
FROM ONLINE_SALE A
INNER JOIN(
            SELECT USER_ID
            FROM USER_INFO
            WHERE EXTRACT(YEAR FROM JOINED)=2021
            ) B
ON A.USER_ID=B.USER_ID
GROUP BY EXTRACT(YEAR FROM A.SALES_DATE), EXTRACT(MONTH FROM A.SALES_DATE)
ORDER BY YEAR, MONTH