-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
        FROM ANIMAL_INS
        WHERE SEX_UPON_INTAKE like 'Intact%') A
INNER JOIN (SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
        WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' or SEX_UPON_OUTCOME LIKE 'Neutered%') B
ON A.ANIMAL_ID=B.ANIMAL_ID