SELECT B.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT OUTER JOIN (select level-1 HOUR from dual connect by level <25) B
ON TO_CHAR(A.DATETIME,'HH24') = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR