SELECT A.USER_ID, A.NICKNAME, CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2 AS "전체주소",REGEXP_REPLACE(TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3')  AS "전화번호"
FROM USED_GOODS_USER A
INNER JOIN
            (SELECT WRITER_ID, COUNT(*)
            FROM USED_GOODS_BOARD
            GROUP BY WRITER_ID
            HAVING COUNT(*)>=3
             )B
ON A.USER_ID=B.WRITER_ID
ORDER BY A.USER_ID DESC