/*식품분류별 가격 가장 비싼것 만 가져오기*/
SELECT A.CATEGORY,A.MAX_PRICE, 
    (SELECT PRODUCT_NAME 
     FROM FOOD_PRODUCT 
     WHERE CATEGORY=A.CATEGORY AND PRICE=A.MAX_PRICE) AS PRODUCT_NAME
FROM (
        SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
        HAVING CATEGORY='과자' OR CATEGORY='국' OR CATEGORY='김치' OR CATEGORY='식용유'
        ) A
ORDER BY MAX_PRICE DESC

