SELECT A.CATEGORY, SUM(SALES) AS SALES
FROM BOOK A
INNER JOIN 
        (SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE EXTRACT(YEAR FROM SALES_DATE)=2022 AND EXTRACT(MONTH FROM SALES_DATE)=1
        GROUP BY BOOK_ID) B
ON A.BOOK_ID=B.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY CATEGORY