SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID,B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM (SELECT BOARD_ID, TITLE
    FROM USED_GOODS_BOARD
    WHERE EXTRACT(YEAR FROM CREATED_DATE)=2022 AND EXTRACT(MONTH FROM CREATED_DATE)=10
      ) A
LEFT OUTER JOIN USED_GOODS_REPLY B
ON A.BOARD_ID= B.BOARD_ID
WHERE B.BOARD_ID IS NOT NULL
ORDER BY CREATED_DATE, TITLE
