SELECT FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT, FOOD_ORDER
WHERE FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
    AND TO_CHAR(PRODUCE_DATE,'YYYY-MM-DD') BETWEEN TO_CHAR(DATE '2022-05-01','YYYY-MM-DD') AND TO_CHAR(DATE '2022-05-31','YYYY-MM-DD')

GROUP BY FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME
ORDER BY SUM(PRICE * AMOUNT) DESC,PRODUCT_ID;