-- 코드를 입력하세요
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'hh24'))AS "HOUR", COUNT(*)
FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'hh24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'hh24')) BETWEEN 9 AND 20
ORDER BY HOUR