-- 코드를 입력하세요
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE>=TO_DATE('20210101','YYYY-MM-DD') AND PUBLISHED_DATE<=TO_DATE('20211231','YYYY-MM-DD')
AND CATEGORY='인문'
ORDER BY PUBLISHED_DATE ASC;