SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE TO_CHAR(A.DATETIME,'YYYY-mm-dd HH24:MI:SS') >TO_CHAR(B.DATETIME,'YYYY-mm-dd HH24:MI:SS')
ORDER BY A.DATETIME